/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.seldon.mih;


import com.google.common.base.Predicates;
import com.seldon.mih.mr.FileUtil;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.web.socket.config.annotation.EnableWebSocket;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableWebSocket
@EnableSwagger2

public class App {

    public static void main(String  [] args) throws Exception {
        System.out.println("Seldon Analytics Engine .....");
       //SpringApplication.run(App.class, args);

        String dPath = "/Users/manigandanm/Documents/workspace/cloudbroker-poc/seldon/src/main/resources/test-docs";
        FileUtil.toFrequencyMap(dPath);
        //List<String> filePaths = FileUtil.getFilePaths(dPath);
        //for(String fp : filePaths) {

            //Map<String, Integer> freqMap = FileUtil.toFrequencyMap(String.format("%s/%s",dPath,fp));
            //Map<String, Double> freqMap = FileUtil.toTFMap(String.format("%s/%s",dPath,fp));
            //System.out.printf("Frequency of %s \n ", fp);
            //System.out.println(freqMap);
            //String outFileName = String.format("%s.out.csv",fp);
            //FileUtil.writeHashMapToCsv(String.format("%s/%s",dPath,outFileName),freqMap);
        //}
        System.out.println(FileUtil.wordFreqMap);
        System.out.println(FileUtil.termFrequencyMap);
        System.out.println(FileUtil.docFreqMap);
        System.out.println(FileUtil.inverseDocumentFrequency);
        System.out.println(FileUtil.tdIDFVector);
    }

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.any())
                .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.boot")))
                .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.cloud")))
                .apis(Predicates.not(RequestHandlerSelectors.basePackage("org.springframework.data.rest.webmvc")))
                .paths(PathSelectors.any())
                .build();
    }
}


